{{- if .Values.ingress.create }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: air-studio-ingress
  namespace: air-platform
  annotations:
    # kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/certificate-arn: {{.Values.ingress.certificateArn}}
    alb.ingress.kubernetes.io/success-codes: 200,302
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/healthcheck-path: /
    alb.ingress.kubernetes.io/healthcheck-port: traffic-port
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: '120'
    alb.ingress.kubernetes.io/healthcheck-timeout-seconds: '5'
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    alb.ingress.kubernetes.io/target-group-attributes: stickiness.enabled=true,stickiness.lb_cookie.duration_seconds=60
    alb.ingress.kubernetes.io/group.name: air-studio
    alb.ingress.kubernetes.io/actions.response-503: '{"type":"fixed-response","fixedResponseConfig":{"contentType":"text/plain","statusCode":"503","messageBody":"서비스가 일시적으로 중단되었습니다. 영업시간: 평일 07:00 - 20:00."}}'
spec:
  ingressClassName: alb
  rules:
    - host: air-studio.{{.Values.platformDomain}}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: air-studio
                port:
                  number: 8800
    - host: air-studio-api.{{.Values.platformDomain}}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: air-studio-fastapi
                port:
                  number: 8801
    - http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: response-503
                port:
                  name: use-annotation 
{{- end }}
